# Generated by Django 6.0.3 on 2026-04-02 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_unit_product',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_product',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_product',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_product',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True),
        ),
    ]
