# Generated by Django 6.0.3 on 2026-04-02 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_price_unit_product_product_stock_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_unit_product',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_product',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_product',
            field=models.CharField(max_length=32),
        ),
    ]
